

login:
    path: /login
    controller: App\Controller\SecurityController::login

admin:
    path: /Admin
    controller: App\Controller\AdminController::index

default:
    path: /Main
    controller: App\Controller\MainController::demandeCode

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::login
